//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH.CleanArchitecture.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CH.CleanArchitecture.Infrastructure.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Buttons_Cancel {
            get {
                return ResourceManager.GetString("Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order.
        /// </summary>
        public static string Buttons_CreateOrder {
            get {
                return ResourceManager.GetString("Buttons_CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string Buttons_CreateUser {
            get {
                return ResourceManager.GetString("Buttons_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Buttons_Delete {
            get {
                return ResourceManager.GetString("Buttons_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Buttons_Details {
            get {
                return ResourceManager.GetString("Buttons_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Buttons_Edit {
            get {
                return ResourceManager.GetString("Buttons_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Buttons_Save {
            get {
                return ResourceManager.GetString("Buttons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string Common_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Common_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Labels_Active {
            get {
                return ResourceManager.GetString("Labels_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change your password.
        /// </summary>
        public static string Labels_ChangePassword {
            get {
                return ResourceManager.GetString("Labels_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Labels_Choose {
            get {
                return ResourceManager.GetString("Labels_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Labels_ConfirmPassword {
            get {
                return ResourceManager.GetString("Labels_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Architecture by Charalambos Hadjiantoniou.
        /// </summary>
        public static string Labels_Copyright {
            get {
                return ResourceManager.GetString("Labels_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Labels_Disabled {
            get {
                return ResourceManager.GetString("Labels_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Labels_Email {
            get {
                return ResourceManager.GetString("Labels_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Labels_Enabled {
            get {
                return ResourceManager.GetString("Labels_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string Labels_FirstPage {
            get {
                return ResourceManager.GetString("Labels_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Labels_Home {
            get {
                return ResourceManager.GetString("Labels_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string Labels_LastPage {
            get {
                return ResourceManager.GetString("Labels_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Labels_Loading {
            get {
                return ResourceManager.GetString("Labels_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Labels_Login {
            get {
                return ResourceManager.GetString("Labels_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Labels_Logout {
            get {
                return ResourceManager.GetString("Labels_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Labels_Name {
            get {
                return ResourceManager.GetString("Labels_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string Labels_NextPage {
            get {
                return ResourceManager.GetString("Labels_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string Labels_NoResults {
            get {
                return ResourceManager.GetString("Labels_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Labels_Of {
            get {
                return ResourceManager.GetString("Labels_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Labels_Password {
            get {
                return ResourceManager.GetString("Labels_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Labels_Phone {
            get {
                return ResourceManager.GetString("Labels_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string Labels_PreviousPage {
            get {
                return ResourceManager.GetString("Labels_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Labels_Processing {
            get {
                return ResourceManager.GetString("Labels_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Labels_Profile {
            get {
                return ResourceManager.GetString("Labels_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Labels_RememberMe {
            get {
                return ResourceManager.GetString("Labels_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Labels_Roles {
            get {
                return ResourceManager.GetString("Labels_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Labels_Search {
            get {
                return ResourceManager.GetString("Labels_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Labels_Searching {
            get {
                return ResourceManager.GetString("Labels_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Labels_Settings {
            get {
                return ResourceManager.GetString("Labels_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Labels_Status {
            get {
                return ResourceManager.GetString("Labels_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Labels_Username {
            get {
                return ResourceManager.GetString("Labels_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Labels_Welcome {
            get {
                return ResourceManager.GetString("Labels_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Navigation_Top_Users {
            get {
                return ResourceManager.GetString("Navigation_Top_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Notifications_Error {
            get {
                return ResourceManager.GetString("Notifications_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been change succesfully.
        /// </summary>
        public static string Notifications_PasswordChange_Success {
            get {
                return ResourceManager.GetString("Notifications_PasswordChange_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Notifications_Success {
            get {
                return ResourceManager.GetString("Notifications_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been created succesfully.
        /// </summary>
        public static string Notifications_UserCreated_Success {
            get {
                return ResourceManager.GetString("Notifications_UserCreated_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated succesfully.
        /// </summary>
        public static string Notifications_UserUpdated_Success {
            get {
                return ResourceManager.GetString("Notifications_UserUpdated_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Notifications_Warning {
            get {
                return ResourceManager.GetString("Notifications_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Roles_Admin {
            get {
                return ResourceManager.GetString("Roles_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super-Admin.
        /// </summary>
        public static string Roles_SuperAdmin {
            get {
                return ResourceManager.GetString("Roles_SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Roles_User {
            get {
                return ResourceManager.GetString("Roles_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Titles_ChangePassword {
            get {
                return ResourceManager.GetString("Titles_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string Titles_EditUser {
            get {
                return ResourceManager.GetString("Titles_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Titles_Login {
            get {
                return ResourceManager.GetString("Titles_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string Titles_NewUser {
            get {
                return ResourceManager.GetString("Titles_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string Titles_UserDetails {
            get {
                return ResourceManager.GetString("Titles_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string Titles_UserProfile {
            get {
                return ResourceManager.GetString("Titles_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Titles_Users {
            get {
                return ResourceManager.GetString("Titles_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is not a valid email address..
        /// </summary>
        public static string Validations_EmailFormat {
            get {
                return ResourceManager.GetString("Validations_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be at least {1} characters long.
        /// </summary>
        public static string Validations_FieldLength {
            get {
                return ResourceManager.GetString("Validations_FieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match.
        /// </summary>
        public static string Validations_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Validations_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is required.
        /// </summary>
        public static string Validations_Required {
            get {
                return ResourceManager.GetString("Validations_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a different password.
        /// </summary>
        public static string Validations_UseDifferentPassword {
            get {
                return ResourceManager.GetString("Validations_UseDifferentPassword", resourceCulture);
            }
        }
    }
}
